### PR TITLE
adding groq model

### PR DESCRIPTION
**Pull request by gioCarBo**
Addition of Groq model.
Related to issue "Groq model implementation #93"

### CODE REVIEW

**Comment by lurenss** [comment]
Hi @gioCarBo, thank you so much for you contribution, the code lgtm, only one thing, can you redirect the merge to the dev/beta branch instead of main, we have recently changed our ci/cd workflow in this way, in the next days we will update also the contributing.md in order to have this clear 😁😁😁

**Comment by lurenss** [comment]
Hii @gioCarBo 
We have messed up a little bith this pull request ahhahaha, can you make another one following this steps:
1) Create a branch from pre/beta
2) Copy the code you have already developed, included the dependencies in requirement.txt and toml file
3) commit with: "feat: adding groq base model"
4) merge into dev/beta

Sorry for the inconvenience 😬😬😬😬

**Comment by gioCarBo** [comment]
Hi @lurenss 
I'm sorry for this. Should I close this PR?

**Comment by PeriniM** [comment]
Hei @gioCarBo I added you as co-author in this PR ae2971c. Thank you!

**Pull request closed without merging**
