### PR TITLE
feat(docloaders): undetected-playwright

### PR DESCRIPTION
**Pull request by QIN2DIM**
Uses a virtually non-intrusive method to hide browser control features. Can bypass most human-authentication algorithms.

### CODE REVIEW

**Comment by PeriniM** [comment]
Really cool! Can you give me a webpage example that can bypass? Let's have a chat on Discord ;)

**Comment by QIN2DIM** [comment]
I wrote some simple examples and put them here https://github.com/QIN2DIM/undetected-playwright/tree/main/examples

In addition, there are special ways to make the browser run in a "headful" way inside the container.

**Comment by QIN2DIM** [comment]
In addition, I maintain a number of projects that directly address multimodal human-computer challenges, but it looks like [Scrapegraph-ai](https://github.com/VinciGit00/Scrapegraph-ai) is still in its "infancy".

So I don't want to do too much intrusive PR, but if the time is right we can talk about it later haha.

**Comment by PeriniM** [comment]
Yess I checked your repo and tested your PR, actually the time is perfect, let's discuss it later ;) DM me on Discord

**Comment by VinciGit00** [comment]
yeah lets talk! write me on mvincig11@gmail.com

**Pull request merged**
