### PR TITLE
make sure embedding model name can be specified for openai embeddings

### PR DESCRIPTION
**Pull request by Robin-des-Bois**

### CODE REVIEW

**Comment by VinciGit00** [comment]
hi, have you tried if it works? on us it does not work ok

**Comment by lrbmike** [comment]
I hope each model to be customizable, I feel terrible when I'm using gemini at the moment

**Comment by Robin-des-Bois** [comment]
When I did this edit in the local package, it worked for me. I only enabled `text-embedding-3-small` in my openai env and hence I got an error. Once I applied the patch, it is working for me now. 
> on us it does not work ok
can you be more precise?

**Comment by VinciGit00** [comment]
give us the code of the example

**Pull request closed without merging**
